Create Materialized View Appuser.V_Cntr_Package_Summary 
refresh force on demand start with sysdate next to_date(concat(to_char(sysdate+1,'dd-mm-yyyy'),' 05:00:00'),'dd-mm-yyyy hh24:mi:ss')
AS
select 
CNTR.CNTR_PACKAGE_UUID,
BKG.BOOKING_UUID,
CNTR.CNTR_NUM,
CNTR.VIRTUAL_CNTR_NUM,
CNTR.CNTR_CDE,
CNTR.SUBST_CNTR_CDE,
CNTR.SOC_IND,
CNTR.EMPTY_IND,
CNTR.IS_ACTUAL_CNTR,
CNTR.MULTIPLE_BL_IND,
CNTR.EMPTY_DSPTCH_LOC,
CNTR.FULL_RETURN_LOC,
CNTR.EMPTY_DSPTCH_DT,
CNTR.FULL_RETURN_DT,
CNTR.FULL_DSPTCH_LOC,
CNTR.EMPTY_RETURN_LOC,
CNTR.FULL_DSPTCH_DT,
CNTR.EMPTY_RETURN_DT,
CNTR.OB_TRANSPORT_TYPE,
CNTR.IB_TRANSPORT_TYPE,
BKG.BOOKING_NUM,
BKG.BOOKING_TYPE,
BKG.BOOKING_STATUS,
BKG.TRAFFIC_MDE,
BKG.PAYMENT_TERM,
BKG.IS_MASTER,
BKG.IS_SELF_CONSLD,
BKG.SHIPPER,
BKG.CONSIGNEE,
BKG.FORWARDER,
BKG.NOTIFY_PARTY1,
BKG.NOTIFY_PARTY2,
BKG.NOTIFY_PARTY3,
BKG.BOOKING_PARTY,
BKG.BOOKING_OFFICE,
BKG.OB_IB_IND,
BKG.TRAFFIC_TERM,
RTE.SHIPPING_ROUTE_UUID,
RTE.POR,
RTE.FND,
RTE.FIRST_POL,
RTE.TRANS_PORT,
RTE.LAST_POD,
OLF.POL_TERMINAL AS FIRST_POL_TERMINAL,
OLL.POD_TERMINAL AS LAST_POD_TERMINAL,
OLF.LOAD_VOYAGE AS F_POL_VOYAGE_UUID,
OLL.DISCHARGE_VOYAGE AS L_POD_VOYAGE_UUID,
min(F_POL.BERTH_DEP_DT_LOC) AS F_POL_DEP_DT,
max(L_POD.PILOT_ARR_DT_LOC) AS L_POD_ARR_DT,
cast ( 1 as numeric(12,2)) AS CNTR_QTY,
cast ( CASE when substr(trim(CNTR.CNTR_CDE),1,2)='20' then 1.0 
when substr(trim(CNTR.CNTR_CDE),1,2)='10' then 0.5 
else  2.0 end as  numeric(12,2)) as TEU_QTY
from CNTR_PACKAGE CNTR JOIN BKG_CNTR_PACKAGE_RELATION B ON CNTR.CNTR_PACKAGE_UUID = B.CNTR_PACKAGE_UUID
JOIN BOOKING BKG ON B.BOOKING_UUID = BKG.BOOKING_UUID
LEFT JOIN SHIPPING_ROUTE RTE ON BKG.SHIPPING_ROUTE_UUID = RTE.SHIPPING_ROUTE_UUID
LEFT JOIN OCEAN_LEG OLF ON OLF.SHIPPING_ROUTE_UUID = RTE.SHIPPING_ROUTE_UUID AND OLF.SEQ_NUM = 1
LEFT JOIN (
SELECT  OL_TMP.SHIPPING_ROUTE_UUID,max(SEQ_NUM) as MAX_SEQ_NUM FROM OCEAN_LEG OL_TMP 
group by OL_TMP.SHIPPING_ROUTE_UUID
) T2 ON RTE.SHIPPING_ROUTE_UUID = T2.SHIPPING_ROUTE_UUID
LEFT JOIN OCEAN_LEG OLL ON T2.SHIPPING_ROUTE_UUID = OLL.SHIPPING_ROUTE_UUID AND T2.MAX_SEQ_NUM = OLL.SEQ_NUM
LEFT JOIN ITS_SCHEDULE F_POL ON F_POL.ITS_VOYAGE_UUID = OLF.LOAD_VOYAGE AND F_POL.GSP_TERMINAL_UUID = OLF.POL_TERMINAL 
LEFT JOIN ITS_SCHEDULE L_POD ON L_POD.ITS_VOYAGE_UUID = OLL.DISCHARGE_VOYAGE AND L_POD.GSP_TERMINAL_UUID = OLL.POD_TERMINAL 
GROUP BY 
CNTR.CNTR_PACKAGE_UUID,
BKG.BOOKING_UUID,
CNTR.CNTR_NUM,
CNTR.VIRTUAL_CNTR_NUM,
CNTR.CNTR_CDE,
CNTR.SUBST_CNTR_CDE,
CNTR.SOC_IND,
CNTR.EMPTY_IND,
CNTR.IS_ACTUAL_CNTR,
CNTR.MULTIPLE_BL_IND,
CNTR.EMPTY_DSPTCH_LOC,
CNTR.FULL_RETURN_LOC,
CNTR.EMPTY_DSPTCH_DT,
CNTR.FULL_RETURN_DT,
CNTR.FULL_DSPTCH_LOC,
CNTR.EMPTY_RETURN_LOC,
CNTR.FULL_DSPTCH_DT,
CNTR.EMPTY_RETURN_DT,
CNTR.OB_TRANSPORT_TYPE,
CNTR.IB_TRANSPORT_TYPE,
BKG.BOOKING_NUM,
BKG.BOOKING_TYPE,
BKG.BOOKING_STATUS,
BKG.TRAFFIC_MDE,
BKG.PAYMENT_TERM,
BKG.IS_MASTER,
BKG.IS_SELF_CONSLD,
BKG.SHIPPER,
BKG.CONSIGNEE,
BKG.FORWARDER,
BKG.NOTIFY_PARTY1,
BKG.NOTIFY_PARTY2,
BKG.NOTIFY_PARTY3,
BKG.BOOKING_PARTY,
BKG.BOOKING_OFFICE,
BKG.OB_IB_IND,
BKG.TRAFFIC_TERM,
RTE.SHIPPING_ROUTE_UUID,
RTE.POR,
RTE.FND,
RTE.FIRST_POL,
RTE.TRANS_PORT,
RTE.LAST_POD,
OLF.POL_TERMINAL ,
OLL.POD_TERMINAL ,
OLF.LOAD_VOYAGE ,
OLL.DISCHARGE_VOYAGE ;


/

CREATE Materialized VIEW V_RPT_MKT_SAL_01 (WEEK_NO ,CNTR_CDE,CNTR_QTY ,TEU_QTY )
refresh force on demand start with sysdate next to_date(concat(to_char(sysdate+1,'dd-mm-yyyy'),' 06:00:00'),'dd-mm-yyyy hh24:mi:ss')
AS 
     SELECT
     AL2.REPORTING_WEEK6 as WEEK_NO,
     AL1.CNTR_CDE,
     SUM(AL1.CNTR_QTY) AS CNTR_QTY,
     SUM(AL1.TEU_QTY) AS TEU_QTY
     FROM V_CNTR_PACKAGE_SUMMARY AL1, 
         O_TIME AL2
     WHERE to_char(AL1.F_POL_DEP_DT,'YYYYMMDD')=AL2.TIME_ID 
     And Al1.Booking_Status In ('Draft', 'Pended', 'Confirmed') 
     GROUP BY      AL2.REPORTING_WEEK6,  AL1.CNTR_CDE;
/