Insert into EBUSER.EB_USER (EB_USER_UUID,USER_ID,USER_PASSWORD,USER_FIRST_NAME,USER_LAST_NAME,SEX,MOBILE_PHONE,EMAIL,DEPART_NAME,POSITION,USER_TYPE,IS_REGISTERED_USER,IS_ADMINISTRATOR,COMPANY_NAME,LOCATION_INFO,POSTAL_CODE,TEL,FAX,WEBSITE,COMPANY_TYPE,MAPPING_ID,SHARE_ID,RECENT_DOC_NUM,APPROVE_STATUS,APPROVE_REMARK,APPROVER,APPROVE_DT,LAST_LOGIN_IP,LAST_LOGIN_DT,IS_ACTIVE,ACTIVATION_DT,REGISTRATION_DT,REC_UPD_DT,REC_UPD_USER_ID,GSP_COUNTRY_CDE,GSP_C_S_P_CDE,GSP_CITY_CDE,AGREEMENT_NUM) 
values ('9c89eb184e044dc1a1370cf80cb14137','ebsystem','46d6e7ddb00ffc7de44e15663fd4bb31','ebsystem','ebsystem','M','','duyj@coscon.com','','','Inner',1,1,'','','','','','','','',null,'','Approved',null,'',sysdate,'0.0.0.0',sysdate,1,null,null,sysdate,'ebsystem',null,null,null,null);
/

Insert into EB_USER (EB_USER_UUID,USER_ID,USER_PASSWORD,USER_FIRST_NAME,USER_LAST_NAME,SEX,MOBILE_PHONE,EMAIL,DEPART_NAME,POSITION,USER_TYPE,IS_REGISTERED_USER,IS_ADMINISTRATOR,COMPANY_NAME,LOCATION_INFO,POSTAL_CODE,TEL,FAX,WEBSITE,COMPANY_TYPE,MAPPING_ID,SHARE_ID,RECENT_DOC_NUM,APPROVE_STATUS,APPROVE_REMARK,APPROVER,APPROVE_DT,LAST_LOGIN_IP,LAST_LOGIN_DT,IS_ACTIVE,ACTIVATION_DT,REGISTRATION_DT,REC_UPD_DT,REC_UPD_USER_ID,GSP_COUNTRY_CDE,GSP_C_S_P_CDE,GSP_CITY_CDE,AGREEMENT_NUM) 
Values ('9c89eb184e044dc1a1370cf80cb14d37','system','cfeba1f492b987f117833f2c672afbe5','system','system','M','','duyj@coscon.com','','','Inner',1,1,'','','','','','','','',Null,'','Approved',Null,'',Sysdate,'0.0.0.0',Sysdate,1,Null,Null,Sysdate,'system',Null,Null,Null,Null);
/

Insert into EB_USER (EB_USER_UUID,USER_ID,USER_PASSWORD,USER_FIRST_NAME,USER_LAST_NAME,SEX,MOBILE_PHONE,EMAIL,DEPART_NAME,POSITION,USER_TYPE,IS_REGISTERED_USER,IS_ADMINISTRATOR,COMPANY_NAME,LOCATION_INFO,POSTAL_CODE,TEL,FAX,WEBSITE,COMPANY_TYPE,MAPPING_ID,SHARE_ID,RECENT_DOC_NUM,APPROVE_STATUS,APPROVE_REMARK,APPROVER,APPROVE_DT,LAST_LOGIN_IP,LAST_LOGIN_DT,IS_ACTIVE,ACTIVATION_DT,REGISTRATION_DT,REC_UPD_DT,REC_UPD_USER_ID,GSP_COUNTRY_CDE,GSP_C_S_P_CDE,GSP_CITY_CDE,AGREEMENT_NUM) 
Values ('1289eb184e044dc1a1370cf80cb14d37','anonymous','dd7b0b1ebecfe55101960f5eb8fc55b2','anonymous','anonymous','M','','duyj@coscon.com','','','Outer',0,0,'','','','','','','','',Null,'','Unapproved',Null,'',Sysdate,'0.0.0.0',Sysdate,1,Null,Null,Sysdate,'anonymous',Null,Null,Null,Null);
/

commit; 